table 'Date Table'
	lineageTag: f59f3c96-11da-4e87-8722-ddf09fe241e5

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6f9c34b1-f5a0-40dc-900c-521f2054fe9d
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: dfc444b5-a706-4886-b28f-32e39662becc
			defaultHierarchy: LocalDateTable_8999966e-164e-40e7-8e38-3277d65791a9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Date Integer'
		dataType: int64
		formatString: 0
		lineageTag: f46bb6e7-8431-4771-8a41-fa77ec5160be
		summarizeBy: sum
		sourceColumn: Date Integer

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: b0c64a9d-0dce-484a-a52b-4dcef33b7507
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = User

	column 'Year Default'
		dataType: string
		lineageTag: f94c2aa5-4af4-4e65-9252-59cb001f2aed
		summarizeBy: none
		sourceColumn: Year Default

		annotation SummarizationSetBy = Automatic

	column YYYY-MM
		dataType: string
		lineageTag: 7a28d7ca-b545-4cfb-9d4e-8fd7972f0b19
		summarizeBy: none
		sourceColumn: YYYY-MM

		annotation SummarizationSetBy = Automatic

	column Month-Year
		dataType: string
		lineageTag: 94b86e26-04cb-439b-a9ac-b3751a9b937e
		summarizeBy: none
		sourceColumn: Month-Year

		annotation SummarizationSetBy = Automatic

	column 'Month Of Year'
		dataType: int64
		formatString: 0
		lineageTag: d6f5de53-bcd0-4c7f-9301-0081ace34ba5
		summarizeBy: none
		sourceColumn: Month Of Year

		annotation SummarizationSetBy = User

	column 'Month Name'
		dataType: string
		lineageTag: f0581209-5624-4126-91cc-7c3f869262ce
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column 'Month Name Short'
		dataType: string
		lineageTag: 976ab958-515d-4d22-83df-f66fec5af80e
		summarizeBy: none
		sourceColumn: Month Name Short

		annotation SummarizationSetBy = Automatic

	column 'Month Name Default'
		dataType: string
		lineageTag: ab267432-2163-4a20-81bd-35ed2944ed1d
		summarizeBy: none
		sourceColumn: Month Name Default

		annotation SummarizationSetBy = Automatic

	column 'Start of Month'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d1280837-e6da-44ba-b20e-2dedfc7589fa
		summarizeBy: none
		sourceColumn: Start of Month

		variation Variation
			isDefault
			relationship: e1de2c22-de38-436a-8841-b30514b25ae6
			defaultHierarchy: LocalDateTable_ba678920-4329-4a08-9c11-03ce291fe0ac.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'End of Month'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 11e188db-3c0f-41e7-b503-480512d10b46
		summarizeBy: none
		sourceColumn: End of Month

		variation Variation
			isDefault
			relationship: f79f5da9-b15c-4243-8625-ad25eda6ca6e
			defaultHierarchy: LocalDateTable_3ae515ad-a96c-4bd4-b023-511ba9fd9e1c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Days in Month'
		dataType: int64
		formatString: 0
		lineageTag: 69dbbbaa-0b87-401d-ad4e-8e8a1a7c992e
		summarizeBy: sum
		sourceColumn: Days in Month

		annotation SummarizationSetBy = Automatic

	column 'ISO Weeknumber'
		dataType: int64
		formatString: 0
		lineageTag: 71e39701-2c1e-4908-bb2f-00e7b77374a4
		summarizeBy: sum
		sourceColumn: ISO Weeknumber

		annotation SummarizationSetBy = Automatic

	column 'ISO Year'
		dataType: int64
		formatString: 0
		lineageTag: 36bae32d-49be-4442-b879-849896d244ab
		summarizeBy: none
		sourceColumn: ISO Year

		annotation SummarizationSetBy = User

	column 'Start of Week'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 860331c6-d1af-4822-96df-ebfe4709c2ec
		summarizeBy: none
		sourceColumn: Start of Week

		variation Variation
			isDefault
			relationship: ba498da5-ec68-4dd5-be05-1fc3b3131ca1
			defaultHierarchy: LocalDateTable_10e525e7-83b3-4dd4-90f5-2b318b9034a2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Quarter Number'
		dataType: int64
		formatString: 0
		lineageTag: e349fe8a-89b0-4802-be37-88434e088da7
		summarizeBy: sum
		sourceColumn: Quarter Number

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 3e3fded8-48d2-4988-903f-d8ceb2df32c9
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Year-Quarter
		dataType: string
		lineageTag: fb849b35-144b-4de9-bc55-7404925b7047
		summarizeBy: none
		sourceColumn: Year-Quarter

		annotation SummarizationSetBy = Automatic

	column 'Day Name'
		dataType: string
		lineageTag: be1ae3a6-2f3f-4cff-acc0-ef10e8e70554
		summarizeBy: none
		sourceColumn: Day Name

		annotation SummarizationSetBy = Automatic

	column 'Day Name Short'
		dataType: string
		lineageTag: 6afcdae9-6d1f-4d75-a77d-2f51e4980bf2
		summarizeBy: none
		sourceColumn: Day Name Short

		annotation SummarizationSetBy = Automatic

	column 'Day of Month Number'
		dataType: int64
		formatString: 0
		lineageTag: 4c5db515-d7ed-4ae3-86e8-a15a884790d3
		summarizeBy: sum
		sourceColumn: Day of Month Number

		annotation SummarizationSetBy = Automatic

	column 'Day of Week Number'
		dataType: int64
		formatString: 0
		lineageTag: fe8ff269-8efd-408a-94b6-9f7ec372b238
		summarizeBy: sum
		sourceColumn: Day of Week Number

		annotation SummarizationSetBy = Automatic

	column 'Day of Year Number'
		dataType: int64
		formatString: 0
		lineageTag: e61d235c-6c4e-4f77-b5d8-55763c55e1cf
		summarizeBy: none
		sourceColumn: Day of Year Number

		annotation SummarizationSetBy = User

	column 'Day Offset'
		dataType: int64
		formatString: 0
		lineageTag: fe83f631-1713-4b1e-a875-843cf47b6db2
		summarizeBy: sum
		sourceColumn: Day Offset

		annotation SummarizationSetBy = Automatic

	column 'Week Offset'
		dataType: int64
		formatString: 0
		lineageTag: 9a5ab016-bf00-4163-a5ad-b322f6274492
		summarizeBy: sum
		sourceColumn: Week Offset

		annotation SummarizationSetBy = Automatic

	column 'Month Offset'
		dataType: int64
		formatString: 0
		lineageTag: 05b56f27-6b97-4d4c-8da4-38052c26a32c
		summarizeBy: sum
		sourceColumn: Month Offset

		annotation SummarizationSetBy = Automatic

	column 'Quarter Offset'
		dataType: int64
		formatString: 0
		lineageTag: f298fd0a-21c5-4baf-bbdd-889b5f772791
		summarizeBy: sum
		sourceColumn: Quarter Offset

		annotation SummarizationSetBy = Automatic

	column 'Year Offset'
		dataType: int64
		formatString: 0
		lineageTag: 3e2c1e0c-480c-4218-9c6c-4b1091895b74
		summarizeBy: none
		sourceColumn: Year Offset

		annotation SummarizationSetBy = User

	column 'Is Weekend'
		dataType: int64
		formatString: 0
		lineageTag: 4c792bec-49d3-4a52-b300-352494f114b9
		summarizeBy: sum
		sourceColumn: Is Weekend

		annotation SummarizationSetBy = Automatic

	column 'Is Weekday'
		dataType: int64
		formatString: 0
		lineageTag: f6ac2797-13b3-486d-8276-b2ba815b8fd2
		summarizeBy: sum
		sourceColumn: Is Weekday

		annotation SummarizationSetBy = Automatic

	partition 'Date Table' = m
		mode: import
		source = ```
				let
				    Today = Date.From( DateTime.LocalNow() ),
				    StartDate = #date(1970, 1, 1),
				    EndDate = Date.EndOfYear( Today ),
				    #"List of Dates" = List.Dates( StartDate, Duration.Days( EndDate - StartDate ) +1, #duration( 1, 0, 0, 0 ) ),
				    #"Converted to Table" = Table.FromList( #"List of Dates", Splitter.SplitByNothing(), type table[Date = Date.Type] ),
				    #"Insert Date Integer" = Table.AddColumn(#"Converted to Table", "Date Integer", each Number.From( Date.ToText( [Date], "yyyyMMdd" ) ), Int64.Type ),
				    #"Insert Year" = Table.AddColumn(#"Insert Date Integer", "Year", each Date.Year([Date]), Int64.Type),
				    // Creates a dynamic year value called 'Current' that moves with the current date. Put this value in a slicer and it automatically switches to the Current period.
				    #"Add Year Default" = Table.AddColumn(#"Insert Year", "Year Default", each if Date.Year( Today ) = [Year] then "Current" else Text.From( [Year] ), type text),
				    #"Insert YYYY-MM" = Table.AddColumn(#"Add Year Default", "YYYY-MM", each Date.ToText( [Date], "yyyy-MM"), type text),
				    #"Insert Month-Year" = Table.AddColumn(#"Insert YYYY-MM", "Month-Year", each Date.ToText( [Date], "MMM yyyy"), type text),
				    #"Insert Month Number" = Table.AddColumn(#"Insert Month-Year", "Month Of Year", each Date.Month([Date]), Int64.Type),
				    #"Insert Month Name" = Table.AddColumn(#"Insert Month Number", "Month Name", each Date.MonthName([Date], "EN-us"), type text),
				    #"Insert Month Name Short" = Table.AddColumn(#"Insert Month Name", "Month Name Short", each Date.ToText( [Date] , "MMM", "EN-us" ), type text),
				    // Creates a dynamic year value called 'Current' that moves with the current date. Put this value in a slicer and it automatically switches to the current period.
				    #"Add Month Name Default" = Table.AddColumn(#"Insert Month Name Short", "Month Name Default", each if Date.Month( Today ) = [Month Of Year] then "Current" else [Month Name], type text ),
				    #"Insert Start of Month" = Table.AddColumn(#"Add Month Name Default", "Start of Month", each Date.StartOfMonth([Date]), type date),
				    #"Inserted End of Month" = Table.AddColumn(#"Insert Start of Month", "End of Month", each Date.EndOfMonth( [Date] ), type date),
				    #"Inserted Days in Month" = Table.AddColumn(#"Inserted End of Month", "Days in Month", each Date.DaysInMonth([Date]), Int64.Type),
				    #"Add ISO Week" = Table.AddColumn(#"Inserted Days in Month", "ISO Weeknumber", each let
				   CurrentThursday = Date.AddDays([Date], 3 - Date.DayOfWeek([Date], Day.Monday ) ),
				   YearCurrThursday = Date.Year( CurrentThursday ),
				   FirstThursdayOfYear = Date.AddDays(#date( YearCurrThursday,1,7),- Date.DayOfWeek(#date(YearCurrThursday,1,1), Day.Friday) ),
				   ISO_Week = Duration.Days( CurrentThursday - FirstThursdayOfYear) / 7 + 1
				in ISO_Week, Int64.Type ),
				    #"Add ISO Year" = Table.AddColumn(#"Add ISO Week", "ISO Year", each Date.Year(  Date.AddDays( [Date], 26 - [ISO Weeknumber] ) ), Int64.Type ),
				    #"Insert Start of Week" = Table.AddColumn(#"Add ISO Year", "Start of Week", each Date.StartOfWeek([Date], Day.Monday ), type date),
				    #"Insert Quarter Number" = Table.AddColumn(#"Insert Start of Week", "Quarter Number", each Date.QuarterOfYear([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Insert Quarter Number", "Quarter", each "Q" & Text.From( Date.QuarterOfYear([Date]) ), type text ),
				    #"Add Year-Quarter" = Table.AddColumn(#"Added Quarter", "Year-Quarter", each Text.From( Date.Year([Date]) ) & "-Q" & Text.From( Date.QuarterOfYear([Date]) ), type text ),
				    #"Insert Day Name" = Table.AddColumn(#"Add Year-Quarter", "Day Name", each Date.DayOfWeekName([Date], "EN-us" ), type text),
				    #"Insert Day Name Short" = Table.AddColumn( #"Insert Day Name", "Day Name Short", each Date.ToText( [Date], "ddd", "EN-us" ), type text),
				    #"Insert Day of Month Number" = Table.AddColumn(#"Insert Day Name Short", "Day of Month Number", each Date.Day([Date]), Int64.Type),
				    // Day.Monday indicates the week starts on Monday. Change this in case you want the week to start on a different date. 
				    #"Insert Day of Week" = Table.AddColumn(#"Insert Day of Month Number", "Day of Week Number", each Date.DayOfWeek( [Date], Day.Monday ), Int64.Type),
				    #"Insert Day of Year" = Table.AddColumn(#"Insert Day of Week", "Day of Year Number", each Date.DayOfYear( [Date] ), Int64.Type),
				    #"Add Day Offset" = Table.AddColumn(#"Insert Day of Year", "Day Offset", each Number.From( [Date] - Date.From( Today ) ) , Int64.Type ),
				    #"Add Week Offset" = Table.AddColumn(#"Add Day Offset", "Week Offset", each Duration.Days( Date.StartOfWeek( [Date], Day.Monday ) - Date.StartOfWeek( Today, Day.Monday ) ) / 7 , Int64.Type ),
				    #"Add Month Offset" = Table.AddColumn(#"Add Week Offset", "Month Offset", each ( [Year] - Date.Year( Today ) ) * 12 + ( [Month Of Year] - Date.Month( Today ) ), Int64.Type ),
				    #"Add Quarter Offset" = Table.AddColumn(#"Add Month Offset", "Quarter Offset", each ( [Year] - Date.Year(Today) ) * 4 + Date.QuarterOfYear( [Date] ) - Date.QuarterOfYear( Today ), Int64.Type ),
				    #"Add Year Offset" = Table.AddColumn(#"Add Quarter Offset", "Year Offset", each [Year] - Date.Year(Today), Int64.Type ),
				    #"Insert Is Weekend" = Table.AddColumn(#"Add Year Offset", "Is Weekend", each if Date.DayOfWeek( [Date] ) >= 5 then 1 else 0, Int64.Type ),
				    #"Insert Is Weekday" = Table.AddColumn(#"Insert Is Weekend", "Is Weekday", each if Date.DayOfWeek( [Date] ) < 5 then 1 else 0, Int64.Type )
				in
				    #"Insert Is Weekday"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

