table PlayersList
	lineageTag: 765cc7cf-8b8b-48cc-a465-39bbfe82c50d

	column id
		dataType: int64
		formatString: 0
		lineageTag: 5b15baf2-d598-47d2-8cdb-e81d92a6aa61
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = User

	column full_name
		dataType: string
		lineageTag: 7172d890-5121-4a46-8c63-e517e5663eda
		summarizeBy: none
		sourceColumn: full_name

		annotation SummarizationSetBy = Automatic

	column first_name
		dataType: string
		lineageTag: d259b839-a8ac-4fdd-8a54-40a1685de543
		summarizeBy: none
		sourceColumn: first_name

		annotation SummarizationSetBy = Automatic

	column last_name
		dataType: string
		lineageTag: e193750b-1378-4b79-b730-365ed8cda589
		summarizeBy: none
		sourceColumn: last_name

		annotation SummarizationSetBy = Automatic

	column is_active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 61e076db-8828-4daf-bd72-c737fcee335a
		summarizeBy: none
		sourceColumn: is_active

		annotation SummarizationSetBy = Automatic

	partition PlayersList = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\charl\OneDrive\Documents\Power BI\datasets\PythonFiles\PlayersList.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"id", Int64.Type}, {"full_name", type text}, {"first_name", type text}, {"last_name", type text}, {"is_active", type logical}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

