table ActivePlayerGamelogs
	lineageTag: e19e015e-c8e6-4271-bd5e-281054c9a72c

	measure 'Avg PPG' = AVERAGE(ActivePlayerGamelogs[PTS])
		lineageTag: fa6d35b7-8272-46f5-a986-2e1a006fdb4f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg AST' = AVERAGE(ActivePlayerGamelogs[AST])
		lineageTag: eed4c037-0903-4f9a-a1c5-d4ecbdaba347

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg REB' = AVERAGE(ActivePlayerGamelogs[REB])
		lineageTag: cd8994c3-9b72-4e63-81ab-92c2ee7bc835

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg STL' = AVERAGE(ActivePlayerGamelogs[STL])
		lineageTag: cb43eb1d-249b-4c00-8ac4-b01da54196e2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SEASON_ID
		dataType: int64
		formatString: 0
		lineageTag: 19397f91-99b7-48b0-90c5-65156a4c4e1a
		summarizeBy: count
		sourceColumn: SEASON_ID

		annotation SummarizationSetBy = Automatic

	column Player_ID
		dataType: int64
		formatString: 0
		lineageTag: 9d66b318-d505-44a1-b322-9946f7b932b5
		summarizeBy: none
		sourceColumn: Player_ID

		annotation SummarizationSetBy = User

	column Game_ID
		dataType: int64
		formatString: 0
		lineageTag: bcf67491-9f7e-4635-bcac-24a58997824d
		summarizeBy: count
		sourceColumn: Game_ID

		annotation SummarizationSetBy = Automatic

	column GAME_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 20a41067-e7ea-4f66-8a6d-fbc3bd87fa01
		summarizeBy: none
		sourceColumn: GAME_DATE

		variation Variation
			isDefault
			relationship: 098ff5ff-207d-4f43-a5de-2bdae97c3dd9
			defaultHierarchy: LocalDateTable_22bde50c-ff7a-4c9c-a526-b0321be76bf1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MATCHUP
		dataType: string
		lineageTag: e05b79f5-5737-401e-883a-9f02e09d3a9e
		summarizeBy: none
		sourceColumn: MATCHUP

		annotation SummarizationSetBy = Automatic

	column WL
		dataType: string
		lineageTag: 49538464-610b-433a-a89d-ef58f92f186e
		summarizeBy: none
		sourceColumn: WL

		annotation SummarizationSetBy = Automatic

	column MIN
		dataType: int64
		formatString: 0
		lineageTag: f9cd5fe2-37fe-4465-976e-c0c56fb4093b
		summarizeBy: sum
		sourceColumn: MIN

		annotation SummarizationSetBy = Automatic

	column FGM
		dataType: int64
		formatString: 0
		lineageTag: 3f67c5a0-9159-444a-8d4a-b137fe6d043c
		summarizeBy: sum
		sourceColumn: FGM

		annotation SummarizationSetBy = Automatic

	column FGA
		dataType: int64
		formatString: 0
		lineageTag: 8b024fb9-9b6f-4a55-b165-f116553ae234
		summarizeBy: sum
		sourceColumn: FGA

		annotation SummarizationSetBy = Automatic

	column FG_PCT
		dataType: double
		lineageTag: 4ea5d90f-c444-4a4d-8771-09768644d704
		summarizeBy: sum
		sourceColumn: FG_PCT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FG3M
		dataType: int64
		formatString: 0
		lineageTag: 9ca127ab-a1c2-45be-a95a-280c6b5a5bc4
		summarizeBy: sum
		sourceColumn: FG3M

		annotation SummarizationSetBy = Automatic

	column FG3A
		dataType: int64
		formatString: 0
		lineageTag: 773314df-5e36-4094-bfb0-4bf6967166e2
		summarizeBy: sum
		sourceColumn: FG3A

		annotation SummarizationSetBy = Automatic

	column FG3_PCT
		dataType: double
		lineageTag: 30fa7c1d-b682-4270-bd4f-8e8d0f962b27
		summarizeBy: sum
		sourceColumn: FG3_PCT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FTM
		dataType: int64
		formatString: 0
		lineageTag: daea3356-acab-4b0a-951e-6f0cebad5a5c
		summarizeBy: sum
		sourceColumn: FTM

		annotation SummarizationSetBy = Automatic

	column FTA
		dataType: int64
		formatString: 0
		lineageTag: 9c08dfa7-22cc-4a88-9b7b-841553900046
		summarizeBy: sum
		sourceColumn: FTA

		annotation SummarizationSetBy = Automatic

	column FT_PCT
		dataType: double
		lineageTag: 23ab389d-aab2-4a38-8b27-5812a10b9712
		summarizeBy: sum
		sourceColumn: FT_PCT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OREB
		dataType: int64
		formatString: 0
		lineageTag: 7284628e-9232-4e24-aa66-fd4ecd2386e0
		summarizeBy: sum
		sourceColumn: OREB

		annotation SummarizationSetBy = Automatic

	column DREB
		dataType: int64
		formatString: 0
		lineageTag: ee173834-fd57-438b-914d-12745f2092a3
		summarizeBy: sum
		sourceColumn: DREB

		annotation SummarizationSetBy = Automatic

	column REB
		dataType: int64
		formatString: 0
		lineageTag: 5c7b317f-998c-43b6-85cd-d0ccbe4d13ce
		summarizeBy: sum
		sourceColumn: REB

		annotation SummarizationSetBy = Automatic

	column AST
		dataType: int64
		formatString: 0
		lineageTag: 50283c2d-3442-492f-accb-c4a745a75441
		summarizeBy: sum
		sourceColumn: AST

		annotation SummarizationSetBy = Automatic

	column STL
		dataType: int64
		formatString: 0
		lineageTag: 9a7047f7-09e3-4144-aab8-6680d8f4bce0
		summarizeBy: sum
		sourceColumn: STL

		annotation SummarizationSetBy = Automatic

	column BLK
		dataType: int64
		formatString: 0
		lineageTag: e8661e43-3bbe-4aa2-baf9-c26dcc00f67c
		summarizeBy: sum
		sourceColumn: BLK

		annotation SummarizationSetBy = Automatic

	column TOV
		dataType: int64
		formatString: 0
		lineageTag: 4ca2a015-b7b5-4139-bbd5-de4099750e3d
		summarizeBy: sum
		sourceColumn: TOV

		annotation SummarizationSetBy = Automatic

	column PF
		dataType: int64
		formatString: 0
		lineageTag: 3c17b33c-a5d2-4d01-97e7-c04ca2b83e18
		summarizeBy: sum
		sourceColumn: PF

		annotation SummarizationSetBy = Automatic

	column PTS
		dataType: int64
		formatString: 0
		lineageTag: c4581ee6-c116-4667-a48f-3cf36c0562e2
		summarizeBy: sum
		sourceColumn: PTS

		annotation SummarizationSetBy = Automatic

	column PLUS_MINUS
		dataType: int64
		formatString: 0
		lineageTag: acc15c91-97c9-44b7-88a6-2c9a454d4be7
		summarizeBy: sum
		sourceColumn: PLUS_MINUS

		annotation SummarizationSetBy = Automatic

	column VIDEO_AVAILABLE
		dataType: int64
		formatString: 0
		lineageTag: 89825cb2-cc8d-47ef-bc1b-170e39f71429
		summarizeBy: sum
		sourceColumn: VIDEO_AVAILABLE

		annotation SummarizationSetBy = Automatic

	partition ActivePlayerGamelogs = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\charl\Documents\GitHub\PowerBI_Version_Control\ActivePlayerGamelogs.csv"),[Delimiter=",", Columns=27, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"SEASON_ID", Int64.Type}, {"Player_ID", Int64.Type}, {"Game_ID", Int64.Type}, {"GAME_DATE", type date}, {"MATCHUP", type text}, {"WL", type text}, {"MIN", Int64.Type}, {"FGM", Int64.Type}, {"FGA", Int64.Type}, {"FG_PCT", type number}, {"FG3M", Int64.Type}, {"FG3A", Int64.Type}, {"FG3_PCT", type number}, {"FTM", Int64.Type}, {"FTA", Int64.Type}, {"FT_PCT", type number}, {"OREB", Int64.Type}, {"DREB", Int64.Type}, {"REB", Int64.Type}, {"AST", Int64.Type}, {"STL", Int64.Type}, {"BLK", Int64.Type}, {"TOV", Int64.Type}, {"PF", Int64.Type}, {"PTS", Int64.Type}, {"PLUS_MINUS", Int64.Type}, {"VIDEO_AVAILABLE", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

